### ISSUE TITLE
PART 1. IntervalTree - Interval 238

### ISSUE THREAD

**Issue by George-Bassilious** [damnePers/java-algorithms-implementation#10]
count cyclomatic complexity by hand for this method. This calculation should be done separately by two people and then cross-checked to see if the results match.

This issue also includes answering the questions under "Complexity" in the report for this function:
1. What is the results for this complex function?
  - Did the two manual calculations and the tool's calculation agree?
  - Is the result clear?
2. Is the function just complex, or just long?
3. What is purpose of the function?
4. Are exceptions taken into account in the measurements from the tool?
5. Is the documentation clear w.r.t. all the possible outcomes?

**Comment by fredriknorlin** [comment]
Manual CCN value: 19
Lizard CCN value: 19

**Comment by damnePers** [comment]
I get the same results

Manual CCN value: 19
Lizard CCN value: 19

**Comment by damnePers** [comment]
Results match, no need for a third party to check.

Results + description added to report.
