### ISSUE TITLE
PART 2. PatricaTrie - addSequence and Matrix - add

### ISSUE THREAD

**Issue by MichaelaSahlgren** [damnePers/java-algorithms-implementation#15]
complete the following tasks described under "Part 2: Coverage measurement & improvement":
Task 1: DIY
Task 2: Coverage improvement
Task 3: Refactoring plan
Task 4: Self-assessment

**Comment by fwallb** [comment]
PatriciaTrie has a very high coverage, 97.2%. Changing method for part 2 to _Matrix - add_.

**Comment by fwallb** [comment]
Task 1: measure branch coverage for Matrix - add

**Comment by fwallb** [comment]
Task 2: coverage improvement for Matrix - add

**Comment by fwallb** [comment]
There is a possible refactoring in Matrix - add. There is no exception thrown when the two matrices size does not match.

**Comment by fwallb** [comment]
bug: travis.yml and pom.xml must be updated to be able to run

**Comment by fwallb** [comment]
Now task 1 and task 2 passes travis!

**Comment by fwallb** [comment]
Task 3: refactoring PatriciaTrie - addSequence
