### ISSUE TITLE
PART 2. IntervalTree - Interval 238

### ISSUE THREAD

**Issue by MichaelaSahlgren** [damnePers/java-algorithms-implementation#16]
complete the following tasks described under "Part 2: Coverage measurement & improvement":
Task 1: DIY
Task 2: Coverage improvement
Task 3: Refactoring plan
Task 4: Self-assessment

**Comment by fredriknorlin** [comment]
Due to Interval already having high coverage I did refactoring on Interval and Coverage on Matrix - compare
