### ISSUE TITLE
PART 1. SegmentTree- FlatSegmentTree

### ISSUE THREAD

**Issue by George-Bassilious** [damnePers/java-algorithms-implementation#2]
Provide answers to the questions:

  1. What are your CNN results? Get complexity using a tool.
  2. Are the function just complex, or also long?
  3. What is the purpose of the function?
  4. Are exceptions taken into account in the given measurements?
  5. Is the documentation clear w.r.t. all the possible outcomes?

**Comment by MichaelaSahlgren** [comment]
This is a spare function that we currently don't plan to analyze. If one of the five selected functions is not suitable, we can switch to this instead.

**Comment by damnePers** [comment]
CCN and short description added to report.
