### ISSUE TITLE
PART 1. RedBlackTree -balanceAfterDelete

### ISSUE THREAD

**Issue by George-Bassilious** [damnePers/java-algorithms-implementation#7]
count cyclomatic complexity by hand for this method. This calculation should be done separately by two people and then cross-checked to see if the results match.

This issue also includes answering the questions under "Complexity" in the report for this function:
1. What is the results for this complex function?
  - Did the two manual calculations and the tool's calculation agree?
  - Is the result clear?
2. Is the function just complex, or just long?
3. What is purpose of the function?
4. Are exceptions taken into account in the measurements from the tool?
5. Is the documentation clear w.r.t. all the possible outcomes?

**Comment by MichaelaSahlgren** [comment]
count cyclomatic complexity by hand for this method. This calculation should be done separately by two people and then cross-checked to see if the results match.

This issue also includes answering the questions under "Complexity" in the report for this function:
1. What is the results for this complex function?
  - Did the two manual calculations and the tool's calculation agree?
  - Is the result clear?
2. Is the function just complex, or just long?
3. What is purpose of the function?
4. Are exceptions taken into account in the measurements from the tool?
5. Is the documentation clear w.r.t. all the possible outcomes?

**Comment by George-Bassilious** [comment]
Manual CCN value : 22
Lizard CCN value :  22

**Comment by MichaelaSahlgren** [comment]
![redblacktree](https://user-images.githubusercontent.com/29230948/108835178-677f2d00-75cf-11eb-8ec9-3ee2f2c34413.jpg)
![balanceafterdeletelizard](https://user-images.githubusercontent.com/29230948/108835187-6a7a1d80-75cf-11eb-8c81-b8e53ea3196d.png)
